CREATE TABLE WKSP_WSFDC.RH_TIP_IDIOMAS
 (COD_TIP_IDIOMA NUMBER(3) NOT NULL,
 DESCRIPCION VARCHAR2(40) NOT NULL,
 USU_INSERCION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
 FEC_INSERCION DATE DEFAULT SYSDATE NOT NULL,
 USU_MODIFICACION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
 FEC_MODIFICACION DATE DEFAULT SYSDATE NOT NULL
 );

COMMENT ON TABLE WKSP_WSFDC.RH_TIP_IDIOMAS IS 'ABM de mantenimiento de tipos de idiomas.';
COMMENT ON COLUMN WKSP_WSFDC.RH_TIP_IDIOMAS.COD_TIP_IDIOMA IS 'Código del tipo de idioma.';
COMMENT ON COLUMN WKSP_WSFDC.RH_TIP_IDIOMAS.DESCRIPCION IS 'Descripción del idioma.';
COMMENT ON COLUMN WKSP_WSFDC.RH_TIP_IDIOMAS.USU_INSERCION IS 'Usuario que realizo la insercion del registro';
COMMENT ON COLUMN WKSP_WSFDC.RH_TIP_IDIOMAS.FEC_INSERCION IS 'Fecha y hora del sistema';
COMMENT ON COLUMN WKSP_WSFDC.RH_TIP_IDIOMAS.USU_MODIFICACION IS 'Usuario que realizo la ultima modificacion del registro';
COMMENT ON COLUMN WKSP_WSFDC.RH_TIP_IDIOMAS.FEC_MODIFICACION IS 'Fecha y hora del sistema en que se realizo la ultima modificacion';
-- Grant/Revoke object privileges 
grant select, insert, update, delete on WKSP_WSFDC.RH_TIP_IDIOMAS to PUBLIC;
