CREATE TABLE WKSP_WSFDC.RH_EMPLEADOS
 (
   COD_PERSONA VARCHAR2(10) NOT NULL,
   COD_PER_EMPRESA VARCHAR2(10) NOT NULL,
   COD_OFICINA NUMBER(3,0) NOT NULL,
   COD_CEN_COSTO NUMBER(3) NOT NULL,
   TIPO VARCHAR2(1) DEFAULT 'M' NOT NULL,
   CARGO VARCHAR2(40),
   TITULO VARCHAR2(40),
   NRO_BAJA VARCHAR2(20),
   NRO_IPS NUMBER(11,0),
   IND_JUB_IPS VARCHAR2(1) DEFAULT 'N' NOT NULL,
   NRO_CAJA VARCHAR2(6),
   SAL_BASE NUMBER(14,2) NOT NULL,
   COD_MONEDA VARCHAR2(3) NOT NULL,
   COD_TURNO NUMBER(3,0) NOT NULL,
   COD_CAT_EMPLEADO NUMBER(3,0) NOT NULL,
   COD_SAL_MINIMO NUMBER(3,0),
   NRO_CTA_ASOCIADA VARCHAR2(15),
   NRO_TARJETA VARCHAR2(20),
   FRE_LIQUIDACION VARCHAR2(1) DEFAULT 'M' NOT NULL,
   FEC_INGRESO DATE NOT NULL,
   FEC_EGRESO DATE,
   FEC_FIN_CONTRATO DATE,
   GRU_SANGUINEO VARCHAR2(4),
   IND_SEG_PRIVADO VARCHAR2(1) DEFAULT 'N',
   COD_ENT_SEGURO NUMBER(5),
   OBSERVACION VARCHAR2(1000),
   USU_INSERCION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
   FEC_INSERCION DATE DEFAULT SYSDATE NOT NULL,
   USU_MODIFICACION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
   FEC_MODIFICACION DATE DEFAULT SYSDATE NOT NULL
 );
COMMENT ON TABLE WKSP_WSFDC.RH_EMPLEADOS IS 'Empleados de la Empresa';
COMMENT ON COLUMN WKSP_WSFDC.RH_EMPLEADOS.COD_PER_EMPRESA IS 'Codigo de la empresa del empleado';
COMMENT ON COLUMN WKSP_WSFDC.RH_EMPLEADOS.COD_OFICINA IS 'Codigo de la oficina del empleado';
COMMENT ON COLUMN WKSP_WSFDC.RH_EMPLEADOS.TIPO IS 'Tipo de Empleado';
COMMENT ON COLUMN WKSP_WSFDC.RH_EMPLEADOS.CARGO IS 'Cargo que ocupa dentro de la Empresa';
COMMENT ON COLUMN WKSP_WSFDC.RH_EMPLEADOS.TITULO IS 'Titulo';
COMMENT ON COLUMN WKSP_WSFDC.RH_EMPLEADOS.NRO_BAJA IS 'Nro. de Baja';
COMMENT ON COLUMN WKSP_WSFDC.RH_EMPLEADOS.NRO_IPS IS 'Nro. de Patronal de IPS';
COMMENT ON COLUMN WKSP_WSFDC.RH_EMPLEADOS.IND_JUB_IPS IS 'Indica si el empleado es jubilado de IPS o no.';
COMMENT ON COLUMN WKSP_WSFDC.RH_EMPLEADOS.NRO_CAJA IS 'Nro. de Padrón en la Caja';
COMMENT ON COLUMN WKSP_WSFDC.RH_EMPLEADOS.SAL_BASE IS 'Salario Base';
COMMENT ON COLUMN WKSP_WSFDC.RH_EMPLEADOS.COD_TURNO IS 'Código del turno.';
COMMENT ON COLUMN WKSP_WSFDC.RH_EMPLEADOS.COD_CAT_EMPLEADO IS 'Código de categoría del empleado.';
COMMENT ON COLUMN WKSP_WSFDC.RH_EMPLEADOS.COD_SAL_MINIMO IS 'Codigo de Tipo de Salario Mínimo';
COMMENT ON COLUMN WKSP_WSFDC.RH_EMPLEADOS.FRE_LIQUIDACION IS 'Frecuencia de Liquidación';
COMMENT ON COLUMN WKSP_WSFDC.RH_EMPLEADOS.FEC_INGRESO IS 'Fecha de Ingreso en la Empresa';
COMMENT ON COLUMN WKSP_WSFDC.RH_EMPLEADOS.FEC_EGRESO IS 'Fecha de Egreso de la Empresa';
COMMENT ON COLUMN WKSP_WSFDC.RH_EMPLEADOS.FEC_FIN_CONTRATO IS 'Fecha fin del contrato en caso de que el contrato del empleado sea por plazo.';
COMMENT ON COLUMN WKSP_WSFDC.RH_EMPLEADOS.GRU_SANGUINEO IS 'Grupo Sanguineo';
COMMENT ON COLUMN WKSP_WSFDC.RH_EMPLEADOS.IND_SEG_PRIVADO IS 'Posee Seguro Privado?';
COMMENT ON COLUMN WKSP_WSFDC.RH_EMPLEADOS.COD_ENT_SEGURO IS 'Nombre del Seguro';
COMMENT ON COLUMN WKSP_WSFDC.RH_EMPLEADOS.OBSERVACION IS 'Observación';
-- Grant/Revoke object privileges 
grant select, insert, update, delete on WKSP_WSFDC.RH_EMPLEADOS to PUBLIC;
