CREATE TABLE WKSP_WSFDC.RH_ASISTENCIAS
 (
   COD_PERSONA VARCHAR2(10) NOT NULL,
   FECHA DATE NOT NULL,
   HOR_NORMAL NUMBER(8,2),
   HOR_30POR NUMBER(8,2),
   HOR_50POR NUMBER(8,2),
   HOR_100POR NUMBER(8,2),
   HOR_130POR NUMBER(8,2),
   USU_INSERCION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
   FEC_INSERCION DATE DEFAULT SYSDATE NOT NULL,
   USU_MODIFICACION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
   FEC_MODIFICACION DATE DEFAULT SYSDATE NOT NULL
 );
COMMENT ON TABLE WKSP_WSFDC.RH_ASISTENCIAS IS 'Asistencias de los Empleados';
COMMENT ON COLUMN WKSP_WSFDC.RH_ASISTENCIAS.COD_PERSONA IS 'Código del empleado.';
COMMENT ON COLUMN WKSP_WSFDC.RH_ASISTENCIAS.FECHA IS 'Fecha de asistencia.';
COMMENT ON COLUMN WKSP_WSFDC.RH_ASISTENCIAS.HOR_NORMAL IS 'Cantidad de horas trabajadas donde su remuneración es normal.';
COMMENT ON COLUMN WKSP_WSFDC.RH_ASISTENCIAS.HOR_30POR IS 'Cantidad de horas trabajadas donde su remuneración corresponde al 30%';
COMMENT ON COLUMN WKSP_WSFDC.RH_ASISTENCIAS.HOR_50POR IS 'Cantidad de horas trabajadas donde su remuneración corresponde al 50%';
COMMENT ON COLUMN WKSP_WSFDC.RH_ASISTENCIAS.HOR_100POR IS 'Cantidad de horas trabajadas donde su remuneración corresponde al 100%';
COMMENT ON COLUMN WKSP_WSFDC.RH_ASISTENCIAS.HOR_130POR IS 'Cantidad de horas trabajadas donde su remuneración corresponde al 130%';
-- Grant/Revoke object privileges
grant select, insert, update, delete on WKSP_WSFDC.RH_ASISTENCIAS to PUBLIC;
