CREATE TABLE WKSP_WSFDC.RH_ESTUDIOS
 (COD_PERSONA VARCHAR2(10) NOT NULL
 ,CURSO VARCHAR2(40) NOT NULL
 ,INSTITUCION VARCHAR2(40) NOT NULL
 ,DURACION VARCHAR2(30) NOT NULL
 ,IND_INTERNO VARCHAR2(1) DEFAULT 'N' NOT NULL
 ,TITULO VARCHAR2(40)
 ,USU_INSERCION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL
 ,FEC_INSERCION DATE DEFAULT SYSDATE NOT NULL
 ,USU_MODIFICACION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL
 FEC_MODIFICACION DATE DEFAULT SYSDATE NOT NULL
 );
COMMENT ON TABLE WKSP_WSFDC.RH_ESTUDIOS IS 'Estudios del Empleado.';
COMMENT ON COLUMN WKSP_WSFDC.RH_ESTUDIOS.CURSO IS 'Curso'
COMMENT ON COLUMN WKSP_WSFDC.RH_ESTUDIOS.INSTITUCION IS 'Institución';
COMMENT ON COLUMN WKSP_WSFDC.RH_ESTUDIOS.DURACION IS 'Duración';
COMMENT ON COLUMN WKSP_WSFDC.RH_ESTUDIOS.IND_INTERNO IS 'Interno?';
COMMENT ON COLUMN WKSP_WSFDC.RH_ESTUDIOS.TITULO IS 'Titulo Obtenido';
-- Grant/Revoke object privileges
grant select, insert, update, delete on WKSP_WSFDC.RH_ESTUDIOS to PUBLIC;
