CREATE TABLE WKSP_WSFDC.RH_ING_AUTOMATICOS
 (
   COD_PERSONA VARCHAR2(5) NOT NULL,
   COD_TIP_INGRESO NUMBER(3,0) NOT NULL,
   FEC_DESDE DATE NOT NULL,
   FEC_HASTA DATE NOT NULL,
   MONTO NUMBER(14,2),
   COD_MONEDA VARCHAR2(3) NOT NULL,
   USU_INSERCION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
   FEC_INSERCION DATE DEFAULT sysdate NOT NULL,
   USU_MODIFICACION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
   FEC_MODIFICACION DATE DEFAULT sysdate NOT NULL
 );
 
COMMENT ON TABLE WKSP_WSFDC.RH_ING_AUTOMATICOS IS 'Ingresos Automaticos de Empleados';
--Grant/Revoke object privileges
grant select, insert, update, delete on WKSP_WSFDC.RH_ING_AUTOMATICOS to PUBLIC;
