CREATE TABLE WKSP_WSFDC.RH_ERR_RELOJES
 (
  NRO_TARJETA VARCHAR2(20) NOT NULL,
  FECHA DATE NOT NULL,
  ARCHIVO VARCHAR2(100) NOT NULL,
  ERROR VARCHAR2(250) NOT NULL,
  USU_INSERCION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
  FEC_INSERCION DATE DEFAULT SYSDATE NOT NULL,
  USU_MODIFICACION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
  FEC_MODIFICACION DATE DEFAULT SYSDATE NOT NULL
 );
COMMENT ON TABLE WKSP_WSFDC.RH_ERR_RELOJES IS 'Errores al recuperar relojes';
-- Grant/Revoke object privileges 
grant select, insert, update, delete on WKSP_WSFDC.RH_ERR_RELOJES to PUBLIC;
