CREATE TABLE WKSP_WSFDC.RH_RELOJES
 (
 COD_PERSONA VARCHAR2(10) NOT NULL,
 FECHA DATE NOT NULL,
 HORA DATE NOT NULL,
 TIPO VARCHAR2(1) NOT NULL,
 NRO_TARJETA VARCHAR2(20) NOT NULL,
 NRO_RELOJ VARCHAR2(15),
 IND_PROCESADO VARCHAR2(1) DEFAULT 'N' NOT NULL,
 USU_INSERCION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
 FEC_INSERCION DATE DEFAULT SYSDATE NOT NULL,
 USU_MODIFICACION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
 FEC_MODIFICACION DATE DEFAULT SYSDATE NOT NULL
 );
COMMENT ON TABLE WKSP_WSFDC.RH_RELOJES IS 'Marcación de Relojes por Empleados';
COMMENT ON COLUMN WKSP_WSFDC.RH_RELOJES.FECHA IS 'Fecha en que se produce el movimiento del reloj para el empleado.';
COMMENT ON COLUMN WKSP_WSFDC.RH_RELOJES.HORA IS 'Hora en que se produce el movimiento del reloj.';
COMMENT ON COLUMN WKSP_WSFDC.RH_RELOJES.TIPO IS 'Tipo de movimiento.';
COMMENT ON COLUMN WKSP_WSFDC.RH_RELOJES.NRO_TARJETA IS 'Número de tarjeta del empleado.';
COMMENT ON COLUMN WKSP_WSFDC.RH_RELOJES.NRO_RELOJ IS 'Número de reloj donde se produjo el movimiento.';
COMMENT ON COLUMN WKSP_WSFDC.RH_RELOJES.IND_PROCESADO IS 'Indica si el registro pudo o no ser procesado.';

--Grant/Revoke object privileges
grant select, insert, update, delete on WKSP_WSFDC.RH_RELOJES to PUBLIC;
