CREATE TABLE WKSP_WSFDC.RH_TURNOS
 (
 COD_TURNO NUMBER(3,0) NOT NULL,
 DESCRIPCION VARCHAR2(35) NOT NULL,
 DIA_DESDE NUMBER(1,0) NOT NULL,
 DIA_HASTA NUMBER(1,0) NOT NULL,
 HOR_DESDE DATE NOT NULL,
 HOR_HASTA DATE NOT NULL,
 IND_HOR_CORTADO VARCHAR2(1) DEFAULT 'N',
 HOR_INI_DESCANSO DATE,
 HOR_FIN_DESCANSO DATE,
 USU_INSERCION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
 FEC_INSERCION DATE DEFAULT SYSDATE NOT NULL,
 USU_MODIFICACION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
 FEC_MODIFICACION DATE DEFAULT SYSDATE NOT NULL
 );

COMMENT ON TABLE WKSP_WSFDC.RH_TURNOS IS 'Tipos de Turnos';
COMMENT ON COLUMN WKSP_WSFDC.RH_TURNOS.COD_TURNO IS 'Código del turno.';
COMMENT ON COLUMN WKSP_WSFDC.RH_TURNOS.DESCRIPCION IS 'Descripción del turno.';
COMMENT ON COLUMN WKSP_WSFDC.RH_TURNOS.DIA_DESDE IS 'Día desde el cual se produce el turno.';
COMMENT ON COLUMN WKSP_WSFDC.RH_TURNOS.DIA_HASTA IS 'Día hasta el cual se produce el turno.';
COMMENT ON COLUMN WKSP_WSFDC.RH_TURNOS.HOR_DESDE IS 'Hora desde la cual se realiza el turno';
COMMENT ON COLUMN WKSP_WSFDC.RH_TURNOS.HOR_HASTA IS 'Hora hasta la cual se produce el turno.';
COMMENT ON COLUMN WKSP_WSFDC.RH_TURNOS.HOR_INI_DESCANSO IS 'Hora desde la cual se realiza el turno';
COMMENT ON COLUMN WKSP_WSFDC.RH_TURNOS.HOR_FIN_DESCANSO IS 'Hora hasta la cual se produce el turno.';
-- Grant/Revoke object privileges 
grant select, insert, update, delete on WKSP_WSFDC.RH_TURNOS to PUBLIC;
