CREATE TABLE WKSP_WSFDC.RH_VACACIONES
 (
   COD_PERSONA VARCHAR2(10) NOT NULL,
   FEC_DESDE DATE NOT NULL,
   FEC_HASTA DATE NOT NULL,
   CAN_DIAS NUMBER(5,0) NOT NULL,
   MONTO NUMBER(14,2) NOT NULL,
   COD_MONEDA VARCHAR2(3) NOT NULL,
   IND_PROCESADO VARCHAR2(1) DEFAULT 'N' NOT NULL,
   COD_PER_AUTORIZADOR VARCHAR2(10),
   PER_DESDE NUMBER(4,0) NOT NULL,
   PER_HASTA NUMBER(4,0) NOT NULL,
   USU_INSERCION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
   FEC_INSERCION DATE DEFAULT SYSDATE NOT NULL,
   USU_MODIFICACION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
   FEC_MODIFICACION DATE DEFAULT SYSDATE NOT NULL
 );
 
COMMENT ON TABLE WKSP_WSFDC.RH_VACACIONES IS 'Vacaciones de los Empleados';
COMMENT ON COLUMN WKSP_WSFDC.RH_VACACIONES.FEC_DESDE IS 'Desde';
COMMENT ON COLUMN WKSP_WSFDC.RH_VACACIONES.FEC_HASTA IS 'Hasta';
COMMENT ON COLUMN WKSP_WSFDC.RH_VACACIONES.CAN_DIAS IS 'Días Hábiles';
COMMENT ON COLUMN WKSP_WSFDC.RH_VACACIONES.MONTO IS 'Monto de las Vacaciones';
COMMENT ON COLUMN WKSP_WSFDC.RH_VACACIONES.IND_PROCESADO IS 'Procesado?';
COMMENT ON COLUMN WKSP_WSFDC.RH_VACACIONES.PER_DESDE IS 'Periodo al cual corresponde la vacación.';
COMMENT ON COLUMN WKSP_WSFDC.RH_VACACIONES.PER_HASTA IS 'Periodo al que corresponde la vacación.';

--Grant/Revoke object privileges
grant select, insert, update, delete on WKSP_WSFDC.RH_VACACIONES to PUBLIC;
