CREATE TABLE WKSP_WSFDC.BA_AFECCIONES
 (COD_AFECCION NUMBER(3,0) NOT NULL,
  IND_DISCAPACITADO VARCHAR2(1) DEFAULT 'N',
  DESCRIPCION VARCHAR2(30) NOT NULL,
  USU_INSERCION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
  FEC_INSERCION DATE DEFAULT SYSDATE NOT NULL,
  USU_MODIFICACION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
  FEC_MODIFICACION DATE DEFAULT SYSDATE NOT NULL
 );
COMMENT ON TABLE WKSP_WSFDC.BA_AFECCIONES IS 'Tipos de Afecciones.';
COMMENT ON COLUMN WKSP_WSFDC.BA_AFECCIONES.COD_AFECCION IS 'Código de Afección.';
COMMENT ON COLUMN WKSP_WSFDC.BA_AFECCIONES.IND_DISCAPACITADO IS 'Indicador de discapacidad fisica.';
COMMENT ON COLUMN WKSP_WSFDC.BA_AFECCIONES.DESCRIPCION IS 'Descripción.';
COMMENT ON COLUMN WKSP_WSFDC.BA_AFECCIONES.USU_INSERCION IS 'Usuario que realizó la inserción del registro.';
COMMENT ON COLUMN WKSP_WSFDC.BA_AFECCIONES.FEC_INSERCION IS 'Fecha en que se insertó el registro.';
COMMENT ON COLUMN WKSP_WSFDC.BA_AFECCIONES.USU_MODIFICACION IS 'Usuario que realizó la última modificación en el registro.';
COMMENT ON COLUMN WKSP_WSFDC.BA_AFECCIONES.FEC_MODIFICACION IS 'Fecha en que se realizó la última modificación en el registro.';
-- Grant/Revoke object privileges 
grant select, insert, update, delete on WKSP_WSFDC.BA_AFECCIONES to PUBLIC;
