CREATE TABLE WKSP_WSFDC.RH_LIQ_SUELDOS
 (
 COD_PERSONA VARCHAR2(10) NOT NULL,
 NRO_SOBRE NUMBER(7,0) NOT NULL,
 COD_TRANSACCION NUMBER(4) NOT NULL,
 COD_MODULO NUMBER(3,0) NOT NULL,
 COD_MODALIDAD NUMBER(3,0) NOT NULL,
 COD_CEN_COSTO NUMBER(3) NOT NULL,
 MONTO NUMBER(14,2) NOT NULL,
 COD_MONEDA VARCHAR2(3) NOT NULL,
 COTIZACION NUMBER(10,4),
 COMPUTABLE NUMBER(5,0),
 VAC_FEC_DESDE DATE,
 ING_NUMERO NUMBER,
 HEX_FEC_HOR_EXTRA DATE,
 DES_NUMERO NUMBER(5,0),
 COD_TIP_INGRESO NUMBER(3,0),
 HOR_COMPUTABLE NUMBER(8,2),
 COD_TIP_DESCUENTO NUMBER(3,0),
 USU_INSERCION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
 FEC_INSERCION DATE DEFAULT SYSDATE NOT NULL,
 USU_MODIFICACION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
 FEC_MODIFICACION DATE DEFAULT SYSDATE NOT NULL
 );

COMMENT ON TABLE WKSP_WSFDC.RH_LIQ_SUELDOS IS 'Liquidaciones de Sueldos de Empleados';
COMMENT ON COLUMN WKSP_WSFDC.RH_LIQ_SUELDOS.NRO_SOBRE IS 'Numero de Sobre';
COMMENT ON COLUMN WKSP_WSFDC.RH_LIQ_SUELDOS.COD_CEN_COSTO IS 'Centro de Costo';
COMMENT ON COLUMN WKSP_WSFDC.RH_LIQ_SUELDOS.MONTO IS 'Monto';
COMMENT ON COLUMN WKSP_WSFDC.RH_LIQ_SUELDOS.COMPUTABLE IS 'Indica el tiempo en dias u horas laboradas de trabajo.';
COMMENT ON COLUMN WKSP_WSFDC.RH_LIQ_SUELDOS.ING_NUMERO IS 'Numero secuencial de Ingreso por empleado';
COMMENT ON COLUMN WKSP_WSFDC.RH_LIQ_SUELDOS.HEX_FEC_HOR_EXTRA IS 'Fecha';
COMMENT ON COLUMN WKSP_WSFDC.RH_LIQ_SUELDOS.DES_NUMERO IS 'Numero secuencial por empleado que identifica el registro.';
COMMENT ON COLUMN WKSP_WSFDC.RH_LIQ_SUELDOS.COD_TIP_INGRESO IS 'Tipo de Ingreso';
COMMENT ON COLUMN WKSP_WSFDC.RH_LIQ_SUELDOS.HOR_COMPUTABLE IS 'Cantidad de horas computables.';
COMMENT ON COLUMN WKSP_WSFDC.RH_LIQ_SUELDOS.COD_TIP_DESCUENTO IS 'Código del Tipo Descuento';

--Grant/Revoke object privileges
grant select, insert, update, delete on WKSP_WSFDC.RH_LIQ_SUELDOS to PUBLIC;
