CREATE TABLE WKSP_WSFDC.RH_IDIOMAS
 (
   COD_PERSONA VARCHAR2(10) NOT NULL,
   COD_TIP_IDIOMA NUMBER(3) NOT NULL,
   IND_HABLA VARCHAR2(1) DEFAULT 'N' NOT NULL,
   IND_LEE VARCHAR2(1) DEFAULT 'N' NOT NULL,
   IND_ESCRIBE VARCHAR2(1) DEFAULT 'N' NOT NULL,
   USU_INSERCION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
   FEC_INSERCION DATE DEFAULT SYSDATE NOT NULL,
   USU_MODIFICACION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
   FEC_MODIFICACION DATE DEFAULT SYSDATE NOT NULL
 );

COMMENT ON TABLE WKSP_WSFDC.RH_IDIOMAS IS 'Idiomas que habla el Empleado';
COMMENT ON COLUMN WKSP_WSFDC.RH_IDIOMAS.IND_HABLA IS 'Habla?';
COMMENT ON COLUMN WKSP_WSFDC.RH_IDIOMAS.IND_LEE IS 'Lee?';
COMMENT ON COLUMN WKSP_WSFDC.RH_IDIOMAS.IND_ESCRIBE IS 'Escribe?';
COMMENT ON COLUMN WKSP_WSFDC.RH_IDIOMAS.USU_INSERCION IS 'Usuario que realizo la insercion del registro';
COMMENT ON COLUMN WKSP_WSFDC.RH_IDIOMAS.FEC_INSERCION IS 'Fecha y hora del sistema';
COMMENT ON COLUMN WKSP_WSFDC.RH_IDIOMAS.USU_MODIFICACION IS 'Usuario que realizo la ultima modificacion del registro';
COMMENT ON COLUMN WKSP_WSFDC.RH_IDIOMAS.FEC_MODIFICACION IS 'Fecha y hora del sistema en que se realizo la ultima modificacion';
-- Grant/Revoke object privileges
grant select, insert, update, delete on WKSP_WSFDC.RH_IDIOMAS to PUBLIC;
