CREATE TABLE WKSP_WSFDC.RH_PAR_EMPRESAS
 (
   COD_EMPRESA VARCHAR2(10) NOT NULL,
   COD_PER_RESPONSABLE VARCHAR2(10),
   IND_APO_IPS_CAJA VARCHAR2(1) DEFAULT 'N',
   PAT_IPS_01 NUMBER(15,0),
   PAT_IPS_02 NUMBER(15,0),
   POR_IPS_EMP NUMBER(5,3),
   POR_IPS_PAT NUMBER(5,3),
   COD_BAN_CAJA VARCHAR2(10),
   POR_CAJ_EMP NUMBER(5,3),
   POR_CAJ_PAT NUMBER(5,3),
   POR_CAJ_EMP_ACT NUMBER(5,3),
   POR_CAJ_PAT_ACT NUMBER(5,3),
   POR_CAJ_RET_SNPP NUMBER(5,3),
   ANO_ACTUAL NUMBER(4,0),
   MES_ACTUAL NUMBER(2,0),
   QUI_ACTUAL NUMBER(1,0),
   POR_DESCUENTOS NUMBER(10,0),
   POR_BONIFICACION NUMBER(8,2),
   FEC_ULT_CIERRE DATE,
   MIN_TOLERANCIA NUMBER(5,0) DEFAULT 0,
   NRO_MJT NUMBER(15),
   COD_TIP_DES_IPS NUMBER(3,0),
   COD_TIP_DES_CAJA NUMBER(3,0),
   COD_TIP_DES_FONDO NUMBER(3,0),
   COD_TIP_ING_VACACION NUMBER(3,0),
   COD_TIP_ING_VAC_PROPORCIONAL NUMBER(3,0),
   COD_TIP_ING_SUELDO NUMBER(3,0),
   COD_TIP_ING_BONIFICACION NUMBER(3,0),
   COD_TIP_ING_PREAVISO NUMBER(3,0),
   COD_TIP_ING_INDEMNIZACION NUMBER(3,0),
   COD_TIP_ING_NORMAL NUMBER(3,0),
   COD_TIP_ING_EXTRAS NUMBER(3,0),
   COD_TIP_ING_30 NUMBER(3,0),
   COD_TIP_ING_50 NUMBER(3,0),
   COD_TIP_ING_100 NUMBER(3,0),
   COD_TIP_ING_130 NUMBER(3,0),
   COD_TIP_ING_AGUINALDO NUMBER(3,0),
   COD_TIP_ING_COMISION NUMBER(3,0),
   COD_TIP_ING_DESTAJO NUMBER(3,0),
   COD_TIP_PROV_VACACION VARCHAR2(3),
   COD_TIP_PROV_AGUINALDO VARCHAR2(3),
   COD_TUR_ADMINISTRATIVO NUMBER(3,0),
   COD_TIP_DES_PRI_SUELDO NUMBER(3,0),
   COD_TIP_DES_AUMENTO NUMBER(3,0),
   COD_TIP_ING_TITULO NUMBER(3,0),
   COD_TIP_ING_ANTIGUEDAD NUMBER(3,0),
   COD_TIP_ING_CARGO NUMBER(3,0),
   COD_TIP_ING_REPRESENTACION NUMBER(3,0),
   COD_TIP_ING_GRATIFICACION NUMBER(3,0),
   FEC_INSERCION DATE DEFAULT SYSDATE NOT NULL,
   USU_MODIFICACION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
   FEC_MODIFICACION DATE DEFAULT SYSDATE NOT NULL,
   USU_INSERCION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL
 );
COMMENT ON TABLE WKSP_WSFDC.RH_PAR_EMPRESAS IS 'Parámetros del Módulo de RRHH para la Empresas';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.COD_EMPRESA IS 'Codigo de la Empresa';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.COD_PER_RESPONSABLE IS 'Responsable por la Empresa';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.IND_APO_IPS_CAJA IS 'Indica si se aporta a IPS o a la Caja';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.PAT_IPS_01 IS 'Nro. Patronal IPS (Principal)';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.PAT_IPS_02 IS 'Nro. Patronal IPS (Secundario)';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.POR_IPS_EMP IS '% IPS Empleado';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.POR_IPS_PAT IS '% IPS Patronal';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.COD_BAN_CAJA IS 'Código del Banco en la Caja';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.POR_CAJ_EMP IS 'Porcentaje que aporta el empleado a la caja';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.POR_CAJ_PAT IS 'Porcentaje que aporta la Patronal a la Caja';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.POR_CAJ_EMP_ACT IS 'Porcentaje que aporta el Empleado para el fondo de Actualización de la Caja';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.POR_CAJ_PAT_ACT IS 'Porcentaje que aporta la Patronal para el fondo de Actualización de la Caja';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.POR_CAJ_RET_SNPP IS 'Porcentaje de Retención para el SNPP';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.ANO_ACTUAL IS 'Año Actual';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.MES_ACTUAL IS 'Mes Actual';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.QUI_ACTUAL IS 'Quincena Actual';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.POR_DESCUENTOS IS '% Descuento';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.POR_BONIFICACION IS '% Bonificación Familiar';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.FEC_ULT_CIERRE IS 'Fecha en que ser realizó el último proceso de cierre.';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.MIN_TOLERANCIA IS 'Minutos de Tolerancia.';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.COD_TIP_DES_IPS IS 'Código del Tipo Descuento';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.COD_TIP_ING_VACACION IS 'Tipo de Ingreso';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.COD_TIP_ING_VAC_PROPORCIONAL IS 'Tipo de Ingreso para las vacaciones proporcionales';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.COD_TIP_ING_SUELDO IS 'Tipo de Ingreso';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.COD_TIP_ING_BONIFICACION IS 'Tipo de Ingreso';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.COD_TIP_ING_PREAVISO IS 'Tipo de Ingreso';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.COD_TIP_ING_INDEMNIZACION IS 'Tipo de Ingreso';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.COD_TIP_ING_NORMAL IS 'Tipo de Ingreso por Horas Normales';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.COD_TIP_ING_EXTRAS IS 'Tipo de Ingreso';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.COD_TIP_ING_30 IS 'Tipo de Ingreso';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.COD_TIP_ING_50 IS 'Tipo de Ingreso';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.COD_TIP_ING_100 IS 'Tipo de Ingreso';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.COD_TIP_ING_130 IS 'Tipo de Ingreso';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.COD_TIP_ING_AGUINALDO IS 'Tipo de Ingreso';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.COD_TIP_ING_COMISION IS 'Tipo de Ingreso para las comisiones';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.COD_TIP_ING_DESTAJO IS 'Tipo de Ingreso por destajo';
comment on column WKSP_WSFDC.RH_PAR_EMPRESAS.COD_TIP_PROV_AGUINALDO is 'Tipo de Ingreso para la provisión de aguinaldo';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.COD_TIP_PROV_VACACION IS 'Tipo de Ingreso para la provisión de vacaciones';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.COD_TUR_ADMINISTRATIVO IS 'Código del turno administrativo';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.COD_TIP_DES_PRI_SUELDO IS 'Tipo de descuento para la caja por el primer sueldo';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.COD_TIP_ING_TITULO IS 'Tipo de Ingreso adicional por título universitario';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.COD_TIP_ING_ANTIGUEDAD IS 'Tipo de Ingreso adicional por antigüedad';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.COD_TIP_ING_CARGO IS 'Tipo de Ingreso adicional por cargo';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.COD_TIP_ING_REPRESENTACION IS 'Tipo de Ingreso por Gastos de Representación';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.FEC_INSERCION IS 'Fecha y hora del sistema en que se insertó el registro';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.USU_MODIFICACION IS 'Usuario que realizó la ultima modificación en el registro';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.FEC_MODIFICACION IS 'Fecha y hora del sistema en que se realizó la última modificación';
COMMENT ON COLUMN WKSP_WSFDC.RH_PAR_EMPRESAS.USU_INSERCION IS 'Usuario que realizó la inserción del registro';

--Grant/Revoke object privileges
grant select, insert, update, delete on WKSP_WSFDC.RH_PAR_EMPRESAS to PUBLIC;
