CREATE TABLE WKSP_WSFDC.RH_NIV_ACADEMICOS
 (
   COD_PERSONA VARCHAR2(10) NOT NULL,
   COD_NIV_ESTUDIO NUMBER(3,0) NOT NULL,
   CUR_ALCANZADO NUMBER(1,0),
   CARRERA VARCHAR2(40),
   UNIVERSIDAD VARCHAR2(40),
   TITULO VARCHAR2(40),
   MOT_ABANDONO VARCHAR2(40),
   USU_INSERCION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
   FEC_INSERCION DATE DEFAULT SYSDATE NOT NULL,
   USU_MODIFICACION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
   FEC_MODIFICACION DATE DEFAULT SYSDATE NOT NULL
 );
COMMENT ON TABLE WKSP_WSFDC.RH_NIV_ACADEMICOS IS 'Niveles Académicos del Empleado';
COMMENT ON COLUMN WKSP_WSFDC.RH_NIV_ACADEMICOS.USU_INSERCION IS 'Usuario que realizó la inserción del registro';
COMMENT ON COLUMN WKSP_WSFDC.RH_NIV_ACADEMICOS.FEC_INSERCION IS 'Fecha y hora del sistema en que se insertó el registro';
COMMENT ON COLUMN WKSP_WSFDC.RH_NIV_ACADEMICOS.USU_MODIFICACION IS 'Usuario que realizó la ultima modificación en el registro';
COMMENT ON COLUMN WKSP_WSFDC.RH_NIV_ACADEMICOS.FEC_MODIFICACION IS 'Fecha y hora del sistema en que se realizó la última modificación';
-- Grant/Revoke object privileges
grant select, insert, update, delete on WKSP_WSFDC.RH_NIV_ACADEMICOS to PUBLIC;

