CREATE TABLE WKSP_WSFDC.RH_ANTECEDENTES
 (
   COD_PERSONA VARCHAR2(10) NOT NULL,
   COD_ENTE NUMBER(5) NOT NULL,
   FECHA DATE NOT NULL,
   MTO_DEUDA NUMBER(14,0),
   COD_MONEDA VARCHAR2(3),
   SAL_DEUDA NUMBER(14,0),
   OBSERVACION VARCHAR2(1000),
   USU_INSERCION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
   FEC_INSERCION DATE DEFAULT SYSDATE NOT NULL,
   USU_MODIFICACION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
   FEC_MODIFICACION DATE DEFAULT SYSDATE NOT NULL
 );
COMMENT ON TABLE WKSP_WSFDC.RH_ANTECEDENTES IS 'Antecedentes de los Empleados';
COMMENT ON COLUMN WKSP_WSFDC.RH_ANTECEDENTES.COD_PERSONA IS 'Codigo de la persona';
COMMENT ON COLUMN WKSP_WSFDC.RH_ANTECEDENTES.COD_ENTE IS 'Código de la Empresa en que el empleado posee deuda';
COMMENT ON COLUMN WKSP_WSFDC.RH_ANTECEDENTES.FECHA IS 'Fecha en que se verificó el antecedente';
COMMENT ON COLUMN WKSP_WSFDC.RH_ANTECEDENTES.MTO_DEUDA IS 'Monto de la Deuda';
COMMENT ON COLUMN WKSP_WSFDC.RH_ANTECEDENTES.SAL_DEUDA IS 'Saldo de la Deuda';
COMMENT ON COLUMN WKSP_WSFDC.RH_ANTECEDENTES.OBSERVACION IS 'Observación que se desee incluir. Ej: No posee antecedentes.';
-- Grant/Revoke object privileges
grant select, insert, update, delete on WKSP_WSFDC.RH_ANTECEDENTES to PUBLIC;
