CREATE TABLE WKSP_WSFDC.RH_DESCUENTOS
 (
   COD_PERSONA VARCHAR2(5) NOT NULL,
   NUMERO NUMBER(5,0) NOT NULL,
   FECHA DATE NOT NULL,
   COD_TIP_DESCUENTO NUMBER(3,0) NOT NULL,
   MONTO NUMBER(14,2),
   COD_MONEDA VARCHAR2(3) NOT NULL,
   PORCENTAJE NUMBER(8,2),
   IND_AUTOMATICO VARCHAR2(1) DEFAULT 'N' NOT NULL,
   IND_PROCESADO VARCHAR2(1) DEFAULT 'N' NOT NULL,
   USU_INSERCION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
   FEC_INSERCION DATE DEFAULT sysdate NOT NULL,
   USU_MODIFICACION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
   FEC_MODIFICACION DATE DEFAULT sysdate NOT NULL
 );

COMMENT ON TABLE WKSP_WSFDC.RH_DESCUENTOS IS 'Descuentos en Liquidación a Empleados';
COMMENT ON COLUMN WKSP_WSFDC.RH_DESCUENTOS.COD_PERSONA IS 'Codigo del empleado';
COMMENT ON COLUMN WKSP_WSFDC.RH_DESCUENTOS.NUMERO IS 'Numero secuencial por empleado que identifica el registro.';
COMMENT ON COLUMN WKSP_WSFDC.RH_DESCUENTOS.FECHA IS 'Fecha Descuento';
COMMENT ON COLUMN WKSP_WSFDC.RH_DESCUENTOS.COD_TIP_DESCUENTO IS 'Tipo de Descuento';
COMMENT ON COLUMN WKSP_WSFDC.RH_DESCUENTOS.MONTO IS 'Monto';
COMMENT ON COLUMN WKSP_WSFDC.RH_DESCUENTOS.PORCENTAJE IS 'Porcentaje de descuento';
COMMENT ON COLUMN WKSP_WSFDC.RH_DESCUENTOS.IND_AUTOMATICO IS 'Es automático?';
COMMENT ON COLUMN WKSP_WSFDC.RH_DESCUENTOS.IND_PROCESADO IS 'Procesado?';
-- Grant/Revoke object privileges
grant select, insert, update, delete on WKSP_WSFDC.RH_DESCUENTOS to PUBLIC;
