CREATE TABLE WKSP_WSFDC.RH_TIP_PROVISIONES
 (
 COD_TIP_PROVISION VARCHAR2(3) NOT NULL,
 COD_TRANSACCION NUMBER(4) NOT NULL,
 COD_MODALIDAD NUMBER(3,0) NOT NULL,
 COD_MODULO NUMBER(3,0) NOT NULL,
 DESCRIPCION VARCHAR2(40) NOT NULL,
 USU_INSERCION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
 FEC_INSERCION DATE DEFAULT SYSDATE NOT NULL,
 USU_MODIFICACION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
 FEC_MODIFICACION DATE DEFAULT SYSDATE NOT NULL
 );
COMMENT ON TABLE WKSP_WSFDC.RH_TIP_PROVISIONES IS 'Tipos de Provisiones';
COMMENT ON COLUMN WKSP_WSFDC.RH_TIP_PROVISIONES.COD_TIP_PROVISION IS 'Código del Tipo de Provisión';
COMMENT ON COLUMN WKSP_WSFDC.RH_TIP_PROVISIONES.DESCRIPCION IS 'Descripcion del Tipo de Provision';
-- Grant/Revoke object privileges 
grant select, insert, update, delete on WKSP_WSFDC.RH_TIP_PROVISIONES to PUBLIC;
