CREATE TABLE WKSP_WSFDC.RH_PUESTOS
 (
 COD_PERSONA VARCHAR2(10) NOT NULL,
 FEC_DESDE DATE NOT NULL,
 FEC_HASTA DATE,
 COD_CAT_EMPLEADO NUMBER(3,0) NOT NULL,
 COD_CEN_COSTO NUMBER(3) NOT NULL,
 CARGO VARCHAR2(40),
 IND_INTERINO VARCHAR2(1) DEFAULT 'N',
 SALARIO NUMBER(14,2),
 COD_MONEDA VARCHAR2(3) NOT NULL,
 COD_OFICINA NUMBER(3),
 USU_INSERCION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
 FEC_INSERCION DATE DEFAULT SYSDATE NOT NULL,
 USU_MODIFICACION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
 FEC_MODIFICACION DATE DEFAULT SYSDATE NOT NULL
 );
COMMENT ON TABLE WKSP_WSFDC.RH_PUESTOS IS 'Puestos de Empleados';
COMMENT ON COLUMN WKSP_WSFDC.RH_PUESTOS.FEC_DESDE IS 'Desde';
COMMENT ON COLUMN WKSP_WSFDC.RH_PUESTOS.FEC_HASTA IS 'Hasta';
COMMENT ON COLUMN WKSP_WSFDC.RH_PUESTOS.CARGO IS 'Cargo';
COMMENT ON COLUMN WKSP_WSFDC.RH_PUESTOS.IND_INTERINO IS 'Interinando?';
COMMENT ON COLUMN WKSP_WSFDC.RH_PUESTOS.SALARIO IS 'Salario';
COMMENT ON COLUMN WKSP_WSFDC.RH_PUESTOS.COD_OFICINA IS 'Codigo de la Oficina';
-- Grant/Revoke object privileges 
grant select, insert, update, delete on WKSP_WSFDC.RH_PUESTOS to PUBLIC;
