CREATE TABLE WKSP_WSFDC.RH_CAT_EMPLEADOS
 (
   COD_CAT_EMPLEADO NUMBER(3,0) NOT NULL,
   DESCRIPCION VARCHAR2(40) NOT NULL,
   USU_INSERCION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
   FEC_INSERCION DATE DEFAULT SYSDATE NOT NULL,
   USU_MODIFICACION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
   FEC_MODIFICACION DATE DEFAULT SYSDATE NOT NULL
 );
COMMENT ON TABLE WKSP_WSFDC.RH_CAT_EMPLEADOS IS 'Cetegorías de Empleados';
COMMENT ON COLUMN WKSP_WSFDC.RH_CAT_EMPLEADOS.COD_CAT_EMPLEADO IS 'Categoria';
COMMENT ON COLUMN WKSP_WSFDC.RH_CAT_EMPLEADOS.DESCRIPCION IS 'Descripción';
-- Grant/Revoke object privileges 
grant select, insert, update, delete on WKSP_WSFDC.RH_CAT_EMPLEADOS to PUBLIC;
