CREATE TABLE WKSP_WSFDC.RH_SANCIONES
 (
   COD_PERSONA VARCHAR2(10) NOT NULL,
   COD_TIP_SANCION NUMBER(3,0) NOT NULL,
   FECHA DATE NOT NULL,
   OBSERVACION VARCHAR2(1000),
   USU_INSERCION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
   FEC_INSERCION DATE DEFAULT SYSDATE NOT NULL,
   USU_MODIFICACION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
   FEC_MODIFICACION DATE DEFAULT SYSDATE NOT NULL
 );

COMMENT ON TABLE WKSP_WSFDC.RH_SANCIONES IS 'Sanciones recibidas por el Empleado'
COMMENT ON COLUMN WKSP_WSFDC.RH_SANCIONES.COD_TIP_SANCION IS 'Tipo de Sancion'
COMMENT ON COLUMN WKSP_WSFDC.RH_SANCIONES.FECHA IS 'Fecha de Sanción'
COMMENT ON COLUMN WKSP_WSFDC.RH_SANCIONES.OBSERVACION IS 'Observacion'
--Grant/Revoke object privileges
grant select, insert, update, delete on WKSP_WSFDC.RH_SANCIONES to PUBLIC;
