CREATE TABLE WKSP_WSFDC.RH_MOVIMIENTOS_HIS
 (
 FECHA DATE NOT NULL,
 HORA VARCHAR2(8) NOT NULL,
 COD_USUARIO VARCHAR2(10) NOT NULL,
 NRO_SECUENCIA NUMBER(3,0) NOT NULL,
 FEC_VALOR DATE,
 MONTO NUMBER(18,2) DEFAULT 0,
 NRO_CUENTA VARCHAR2(15),
 COD_MONEDA VARCHAR2(3) NOT NULL,
 COD_OFICINA NUMBER(3,0),
 COD_ERROR VARCHAR2(10),
 COD_RETENCION NUMBER(3,0),
 FEC_FIN_RETENCION DATE,
 EST_CUENTA VARCHAR2(1),
 ESTADO VARCHAR2(1) DEFAULT 'N' NOT NULL,
 COD_CAUSA NUMBER(3,0),
 COD_BANCO NUMBER(3,0),
 COD_OFI_ORIGEN NUMBER(3,0) NOT NULL,
 CONCEPTO VARCHAR2(35),
 COD_TASA NUMBER(3,0),
 VAL_TASA NUMBER(20,4) DEFAULT 0,
 COD_RUBRO VARCHAR2(15),
 COD_REF_CAMBIO VARCHAR2(3),
 REVERSADO VARCHAR2(1) DEFAULT 'N' NOT NULL,
 COD_USU_REVERSION VARCHAR2(10),
 HOR_REVERSION VARCHAR2(8),
 EMI_AVISO VARCHAR2(1) DEFAULT 'N',
 COD_TRA_PADRE NUMBER(4) NOT NULL,
 COD_MOD_PADRE NUMBER(3,0) NOT NULL,
 COD_MAD_PADRE NUMBER(3,0) NOT NULL,
 COD_TRANSACCION NUMBER(4),
 COD_MODULO NUMBER(3,0),
 COD_MODALIDAD NUMBER(3,0),
 MTO_EQU_LOCAL NUMBER(18,2) DEFAULT 0,
 NRO_CAJA NUMBER(3,0),
 COTIZACION NUMBER(14,4) DEFAULT 0,
 COD_BCO_CENTRAL VARCHAR2(6),
 NRO_DOCUMENTO NUMBER(15,0),
 NRO_DOCUMENTO2 NUMBER(15,0),
 NRO_DOCUMENTO3 NUMBER(15,0),
 NRO_DOCUMENTO4 NUMBER(15,0),
 PROTEGIDO VARCHAR2(1) DEFAULT 'N',
 TIP_MOV_RUBRO VARCHAR2(1),
 COD_AUTORIZACION NUMBER(10,0),
 COD_USU_AUTORIZADOR VARCHAR2(10),
 COD_TIP_OPE_CAMBIO VARCHAR2(3),
 USU_INSERCION VARCHAR2(10) DEFAULT USER NOT NULL,
 FEC_INSERCION DATE DEFAULT SYSDATE NOT NULL,
 USU_MODIFICACION VARCHAR2(10) DEFAULT USER NOT NULL,
 FEC_MODIFICACION DATE DEFAULT SYSDATE NOT NULL
 );
COMMENT ON TABLE WKSP_WSFDC.RH_MOVIMIENTOS_HIS IS 'Movimientos Diarios. Contiene todos los movimientos generados en el dia de Hoy, del modulo de RRHH';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.FECHA IS 'Fecha de la transaccion.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.HORA IS 'Hora del movimiento.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.COD_USUARIO IS 'Código de operador.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.NRO_SECUENCIA IS 'Numero de secuencia.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.FEC_VALOR IS 'Fecha valor de la transaccion.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.MONTO IS 'Importe de la transaccion.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.NRO_CUENTA IS 'Numero de cuenta.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.COD_MONEDA IS 'Código de moneda.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.COD_OFICINA IS 'Código de oficina.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.COD_ERROR IS 'Código de error.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.COD_RETENCION IS 'Código de retencion.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.FEC_FIN_RETENCION IS 'Fecha fin de la retencion.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.EST_CUENTA IS 'Estado de la cuenta. (En caso de que se haga cambio de estado).';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.ESTADO IS 'Estado del movimiento. ( ).';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.COD_CAUSA IS 'Código de causa de bloqueo.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.COD_BANCO IS 'Código de banco.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.COD_OFI_ORIGEN IS 'Código de oficina origen.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.CONCEPTO IS 'Concepto del movimiento.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.COD_TASA IS 'Código de tasa.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.VAL_TASA IS 'Importe de la tasa.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.COD_RUBRO IS 'Código de cuenta contable.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.COD_REF_CAMBIO IS 'Código de referencia.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.REVERSADO IS 'Reversado. (N=NO  S=SI).';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.COD_USU_REVERSION IS 'Operador de reversion.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.HOR_REVERSION IS 'Hora de reversion.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.EMI_AVISO IS 'Emitir aviso. (N=NO  S=SI).';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.COD_TRA_PADRE IS 'Código de transaccion padre.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.COD_MOD_PADRE IS 'Código de modulo padre.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.COD_MAD_PADRE IS 'Código de modalidad padre.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.COD_TRANSACCION IS 'Código de transaccion hijo.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.COD_MODULO IS 'Código de modulo.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.COD_MODALIDAD IS 'Código de modalidad.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.MTO_EQU_LOCAL IS 'Importe equivalente en GS.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.NRO_CAJA IS 'Numero de caja.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.COTIZACION IS 'Cotizacion.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.COD_BCO_CENTRAL IS 'Código en el BCP.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.NRO_DOCUMENTO IS 'Numero de documento.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.NRO_DOCUMENTO2 IS 'Número de documento.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.NRO_DOCUMENTO3 IS 'Numero de documento.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.NRO_DOCUMENTO4 IS 'Numero de documento.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.PROTEGIDO IS 'Protegido. (N=NO  S=SI).';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.TIP_MOV_RUBRO IS 'Tipo de movimiento.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.COD_AUTORIZACION IS 'Numero de autorizacion.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.COD_USU_AUTORIZADOR IS 'Código de autorizacion.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.COD_TIP_OPE_CAMBIO IS 'Código de tipo de operacion de cambio.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.USU_INSERCION IS 'Usuario que realizó la inserción del registro.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.FEC_INSERCION IS 'Fecha en que se insertó el registro.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.USU_MODIFICACION IS 'Usuario que realizó la última modificación en el registro.';
COMMENT ON COLUMN WKSP_WSFDC.RH_MOVIMIENTOS_HIS.FEC_MODIFICACION IS 'Fecha en que se realizó la última modificación en el registro.';

--Grant/Revoke object privileges
grant select, insert, update, delete on WKSP_WSFDC.RH_MOVIMIENTOS_HIS to PUBLIC;
