CREATE TABLE WKSP_WSFDC.RH_INGRESOS
 (
 COD_PERSONA VARCHAR2(10) NOT NULL,
 NUMERO NUMBER NOT NULL,
 FECHA DATE NOT NULL,
 COD_TIP_INGRESO NUMBER(3,0) NOT NULL,
 MONTO NUMBER(14,2) NOT NULL,
 COD_MONEDA VARCHAR2(3) NOT NULL,
 IND_AUTOMATICO VARCHAR2(1) DEFAULT 'N' NOT NULL,
 IND_PROCESADO VARCHAR2(1) DEFAULT 'N' NOT NULL,
 COD_PER_AUTORIZADOR VARCHAR2(10),
 OBSERVACION VARCHAR2(1000),
 USU_INSERCION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
 FEC_INSERCION DATE DEFAULT SYSDATE NOT NULL,
 USU_MODIFICACION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
 FEC_MODIFICACION DATE DEFAULT SYSDATE NOT NULL
 );

COMMENT ON TABLE WKSP_WSFDC.RH_INGRESOS IS 'Ingresos del Empleado';
COMMENT ON COLUMN WKSP_WSFDC.RH_INGRESOS.NUMERO IS 'Numero secuencial de Ingreso por empleado';
COMMENT ON COLUMN WKSP_WSFDC.RH_INGRESOS.FECHA IS 'Fec. Ingreso';
COMMENT ON COLUMN WKSP_WSFDC.RH_INGRESOS.COD_TIP_INGRESO IS 'Tipo de Ingreso';
COMMENT ON COLUMN WKSP_WSFDC.RH_INGRESOS.MONTO IS 'Monto Ingreso';
COMMENT ON COLUMN WKSP_WSFDC.RH_INGRESOS.IND_AUTOMATICO IS 'Es automático?';
COMMENT ON COLUMN WKSP_WSFDC.RH_INGRESOS.IND_PROCESADO IS 'Procesado?';
COMMENT ON COLUMN WKSP_WSFDC.RH_INGRESOS.OBSERVACION IS 'Observación';

--Grant/Revoke object privileges
grant select, insert, update, delete on WKSP_WSFDC.RH_INGRESOS to PUBLIC;
