CREATE TABLE WKSP_WSFDC.RH_AUSENCIAS
 (
   COD_PERSONA VARCHAR2(10) NOT NULL,
   COD_TIP_AUSENCIA VARCHAR2(3) NOT NULL,
   FEC_INICIO DATE NOT NULL,
   FEC_FIN DATE NOT NULL,
   IND_JUSTIFICADO VARCHAR2(1) DEFAULT 'N' NOT NULL,
   IND_PROCESADO VARCHAR2(1) DEFAULT 'N' NOT NULL,
   USU_INSERCION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
   FEC_INSERCION DATE DEFAULT SYSDATE NOT NULL,
   USU_MODIFICACION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
   FEC_MODIFICACION DATE DEFAULT SYSDATE NOT NULL
 );

COMMENT ON TABLE WKSP_WSFDC.RH_AUSENCIAS IS 'Ausencias de los Empleados';
COMMENT ON COLUMN WKSP_WSFDC.RH_AUSENCIAS.COD_PERSONA IS 'Codigo de la persona';
COMMENT ON COLUMN WKSP_WSFDC.RH_AUSENCIAS.COD_TIP_AUSENCIA IS 'Tipo de Ausencias';
COMMENT ON COLUMN WKSP_WSFDC.RH_AUSENCIAS.FEC_INICIO IS 'Inicio';
COMMENT ON COLUMN WKSP_WSFDC.RH_AUSENCIAS.FEC_FIN IS 'Final';
COMMENT ON COLUMN WKSP_WSFDC.RH_AUSENCIAS.IND_JUSTIFICADO IS 'Indicador de SI o NO';
COMMENT ON COLUMN WKSP_WSFDC.RH_AUSENCIAS.IND_PROCESADO IS 'Procesado?';
-- Grant/Revoke object privileges
grant select, insert, update, delete on WKSP_WSFDC.RH_AUSENCIAS to PUBLIC;
