CREATE TABLE WKSP_WSFDC.RH_TIP_SANCIONES
 (
 COD_TIP_SANCION NUMBER(3,0) NOT NULL,
 DESCRIPCION VARCHAR2(50) NOT NULL,
 USU_INSERCION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
 FEC_INSERCION VARCHAR2(240) NOT NULL,
 USU_MODIFICACION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
 FEC_MODIFICACION DATE DEFAULT SYSDATE NOT NULL
 );
COMMENT ON TABLE WKSP_WSFDC.RH_TIP_SANCIONES IS 'Permite definir los tipos de sanciones del empleado.';
COMMENT ON COLUMN WKSP_WSFDC.RH_TIP_SANCIONES.COD_TIP_SANCION IS 'Cógido del Tipo de Sanción';
COMMENT ON COLUMN WKSP_WSFDC.RH_TIP_SANCIONES.DESCRIPCION IS 'Descripción';
-- Grant/Revoke object privileges 
grant select, insert, update, delete on WKSP_WSFDC.RH_TIP_SANCIONES to PUBLIC;
