CREATE TABLE WKSP_WSFDC.RH_PER_PREAVISO
 (
 ANO_DESDE NUMBER(2,0) NOT NULL,
 ANO_HASTA NUMBER(2,0) NOT NULL,
 DESCRIPCION VARCHAR2(40) NOT NULL,
 DIAS_PREAVISO NUMBER(3,0),
 USU_INSERCION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
 FEC_INSERCION DATE DEFAULT SYSDATE NOT NULL,
 USU_MODIFICACION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
 FEC_MODIFICACION DATE DEFAULT SYSDATE NOT NULL
 );

COMMENT ON TABLE WKSP_WSFDC.RH_PER_PREAVISO IS 'Periodos de Preaviso';
COMMENT ON COLUMN WKSP_WSFDC.RH_PER_PREAVISO.ANO_DESDE IS 'Desde';
COMMENT ON COLUMN WKSP_WSFDC.RH_PER_PREAVISO.ANO_HASTA IS 'Hasta';
COMMENT ON COLUMN WKSP_WSFDC.RH_PER_PREAVISO.DESCRIPCION IS 'Descripción';
COMMENT ON COLUMN WKSP_WSFDC.RH_PER_PREAVISO.DIAS_PREAVISO IS 'Dias';

--Grant/Revoke object privileges
grant select, insert, update, delete on WKSP_WSFDC.RH_PER_PREAVISO to PUBLIC;
