CREATE TABLE WKSP_WSFDC.RH_TIP_DESCUENTOS
 (
 COD_TIP_DESCUENTO NUMBER(3,0) NOT NULL,
 DESCRIPCION VARCHAR2(50) NOT NULL,
 COD_TRANSACCION NUMBER(4) NOT NULL,
 COD_MODULO NUMBER(3,0) NOT NULL,
 COD_MODALIDAD NUMBER(3,0) NOT NULL,
 PRIORIDAD NUMBER(2,0) NOT NULL,
 TIPO VARCHAR2(1) DEFAULT 'O' NOT NULL,
 USU_INSERCION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
 FEC_INSERCION DATE DEFAULT SYSDATE NOT NULL,
 USU_MODIFICACION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
 FEC_MODIFICACION DATE DEFAULT SYSDATE NOT NULL
 );
COMMENT ON TABLE WKSP_WSFDC.RH_TIP_DESCUENTOS IS 'Tipos de Descuentos';
COMMENT ON COLUMN WKSP_WSFDC.RH_TIP_DESCUENTOS.COD_TIP_DESCUENTO IS 'Código del Tipo Descuento';
COMMENT ON COLUMN WKSP_WSFDC.RH_TIP_DESCUENTOS.DESCRIPCION IS 'Descripción';
COMMENT ON COLUMN WKSP_WSFDC.RH_TIP_DESCUENTOS.PRIORIDAD IS 'Prioridad';
COMMENT ON COLUMN WKSP_WSFDC.RH_TIP_DESCUENTOS.TIPO IS 'Tipo de descuento.';
COMMENT ON COLUMN WKSP_WSFDC.RH_TIP_DESCUENTOS.USU_INSERCION IS 'Usuario que realizo la insercion del registro';
COMMENT ON COLUMN WKSP_WSFDC.RH_TIP_DESCUENTOS.FEC_INSERCION IS 'Fecha y Hora del sistema en que se inserto el registro';
COMMENT ON COLUMN WKSP_WSFDC.RH_TIP_DESCUENTOS.USU_MODIFICACION IS 'Usuario que realizo la ultima modificacion en el registro';
COMMENT ON COLUMN WKSP_WSFDC.RH_TIP_DESCUENTOS.FEC_MODIFICACION IS 'Fecha y hora del sistema en que se realizo la ultima modificacion';
-- Grant/Revoke object privileges 
grant select, insert, update, delete on WKSP_WSFDC.RH_TIP_DESCUENTOS to PUBLIC;
