CREATE TABLE WKSP_WSFDC.RH_ERRORES
 (
 CLAVE VARCHAR2(30) NOT NULL,
 ERROR VARCHAR2(250) NOT NULL,
 USU_INSERCION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
 FEC_INSERCION DATE DEFAULT SYSDATE NOT NULL, 
 USU_MODIFICACION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
 FEC_MODIFICACION DATE DEFAULT SYSDATE NOT NULL
 );
COMMENT ON TABLE WKSP_WSFDC.RH_ERRORES IS 'Errores del Sistema';
-- Grant/Revoke object privileges 
grant select, insert, update, delete on WKSP_WSFDC.RH_ERRORES to PUBLIC;
--
