CREATE TABLE WKSP_WSFDC.RH_TIP_DESEMPENOS
 (
  COD_TIP_DESEMPENO NUMBER(3,0) NOT NULL,
  DESCRIPCION VARCHAR2(50) NOT NULL,
  USU_INSERCION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
  FEC_INSERCION DATE DEFAULT SYSDATE NOT NULL,
  USU_MODIFICACION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
  FEC_MODIFICACION DATE DEFAULT SYSDATE NOT NULL
 );
COMMENT ON TABLE WKSP_WSFDC.RH_TIP_DESEMPENOS IS 'Tipos de Desempeños';
COMMENT ON COLUMN WKSP_WSFDC.RH_TIP_DESEMPENOS.COD_TIP_DESEMPENO IS 'Código del Tipo de Desempeño';
COMMENT ON COLUMN WKSP_WSFDC.RH_TIP_DESEMPENOS.DESCRIPCION IS 'Descripción del tipo de desempeño';
-- Grant/Revoke object privileges 
grant select, insert, update, delete on WKSP_WSFDC.RH_TIP_DESEMPENOS to PUBLIC;
