CREATE TABLE WKSP_WSFDC.RH_TIP_AUSENCIAS
 (
 COD_TIP_AUSENCIA VARCHAR2(3) NOT NULL,
 DESCRIPCION VARCHAR2(40) NOT NULL,
 IND_GOC_SUELDO VARCHAR2(1) DEFAULT 'N' NOT NULL,
 POR_SUELDO NUMBER(5,2),
 USU_INSERCION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
 FEC_INSERCION DATE DEFAULT SYSDATE NOT NULL,
 USU_MODIFICACION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
 FEC_MODIFICACION DATE DEFAULT SYSDATE NOT NULL
 );
COMMENT ON TABLE WKSP_WSFDC.RH_TIP_AUSENCIAS IS 'Ausencias del Empleado.';
COMMENT ON COLUMN WKSP_WSFDC.RH_TIP_AUSENCIAS.COD_TIP_AUSENCIA IS 'Tipo de Ausencias.';
COMMENT ON COLUMN WKSP_WSFDC.RH_TIP_AUSENCIAS.DESCRIPCION IS 'Descripción.';
COMMENT ON COLUMN WKSP_WSFDC.RH_TIP_AUSENCIAS.IND_GOC_SUELDO IS 'Con goce de sueldos? Valores posibles: Si o No';
COMMENT ON COLUMN WKSP_WSFDC.RH_TIP_AUSENCIAS.POR_SUELDO IS 'Porcentaje de sueldo a cobrar por la ausencia.';
COMMENT ON COLUMN WKSP_WSFDC.RH_TIP_AUSENCIAS.USU_INSERCION IS 'Usuario que realizó la inserción del registro.';
COMMENT ON COLUMN WKSP_WSFDC.RH_TIP_AUSENCIAS.FEC_INSERCION IS 'Fecha y hora del sistema en que se insertó el registro.';
COMMENT ON COLUMN WKSP_WSFDC.RH_TIP_AUSENCIAS.USU_MODIFICACION IS 'Usuario que realizó la última modificación en el registro.';
COMMENT ON COLUMN WKSP_WSFDC.RH_TIP_AUSENCIAS.FEC_MODIFICACION IS 'Fecha y Hora del sistema en que se realizó la última modificación.';
-- Grant/Revoke object privileges 
grant select, insert, update, delete on WKSP_WSFDC.RH_TIP_AUSENCIAS to PUBLIC;
