CREATE TABLE WKSP_WSFDC.BA_PER_AFECCIONES
 (
   COD_PERSONA VARCHAR2(10) NOT NULL,
   COD_AFECCION NUMBER(5,0) NOT NULL,
   OBSERVACION VARCHAR2(50),
   USU_INSERCION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
   FEC_INSERCION DATE DEFAULT SYSDATE NOT NULL,
   USU_MODIFICACION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
   FEC_MODIFICACION DATE DEFAULT SYSDATE NOT NULL,
   CONSTRAINT PK_BA_PER_AFECCIONES PRIMARY KEY (COD_PERSONA,COD_AFECCION)
 );

COMMENT ON TABLE WKSP_WSFDC.BA_PER_AFECCIONES IS 'Personas con Afecciones.';
COMMENT ON COLUMN WKSP_WSFDC.BA_PER_AFECCIONES.COD_PERSONA IS 'Código de la Persona.';
COMMENT ON COLUMN WKSP_WSFDC.BA_PER_AFECCIONES.COD_AFECCION IS 'Código de la Afección.';
COMMENT ON COLUMN WKSP_WSFDC.BA_PER_AFECCIONES.OBSERVACION IS 'Observación de la Afección de la Persona.';
COMMENT ON COLUMN WKSP_WSFDC.BA_PER_AFECCIONES.USU_INSERCION IS 'Usuario que realizó la inserción del registro.';
COMMENT ON COLUMN WKSP_WSFDC.BA_PER_AFECCIONES.FEC_INSERCION IS 'Fecha en que se insertó el registro.';
COMMENT ON COLUMN WKSP_WSFDC.BA_PER_AFECCIONES.USU_MODIFICACION IS 'Usuario que realizó la última modificación en el registro.';
COMMENT ON COLUMN WKSP_WSFDC.BA_PER_AFECCIONES.FEC_MODIFICACION IS 'Fecha en que se realizó la última modificación en el registro.';
-- Grant/Revoke object privileges 
grant select, insert, update, delete on WKSP_WSFDC.BA_PER_AFECCIONES to PUBLIC;
