CREATE TABLE WKSP_WSFDC.RH_TIP_INGRESOS
 (
 COD_TIP_INGRESO NUMBER(3,0) NOT NULL,
 COD_TRANSACCION NUMBER(4) NOT NULL,
 COD_MODULO NUMBER(3,0) NOT NULL,
 COD_MODALIDAD NUMBER(3,0) NOT NULL,
 DESCRIPCION VARCHAR2(50) NOT NULL,
 IND_IMPONIBLE VARCHAR2(1) DEFAULT 'N' NOT NULL,
 IND_ACU_AGUINALDO VARCHAR2(1) DEFAULT 'N' NOT NULL,
 USU_INSERCION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
 FEC_INSERCION DATE DEFAULT SYSDATE NOT NULL,
 USU_MODIFICACION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
 FEC_MODIFICACION DATE DEFAULT SYSDATE NOT NULL
 );
COMMENT ON TABLE WKSP_WSFDC.RH_TIP_INGRESOS IS 'Tipos de Ingresos';
COMMENT ON COLUMN WKSP_WSFDC.RH_TIP_INGRESOS.COD_TIP_INGRESO IS 'Tipo de Ingreso';
COMMENT ON COLUMN WKSP_WSFDC.RH_TIP_INGRESOS.DESCRIPCION IS 'Descripción';
COMMENT ON COLUMN WKSP_WSFDC.RH_TIP_INGRESOS.IND_IMPONIBLE IS 'Paga IPS?';
COMMENT ON COLUMN WKSP_WSFDC.RH_TIP_INGRESOS.IND_ACU_AGUINALDO IS 'Acumula Aguinaldo?';
-- Grant/Revoke object privileges 
grant select, insert, update, delete on WKSP_WSFDC.RH_TIP_INGRESOS to PUBLIC;

