CREATE TABLE WKSP_WSFDC.RH_SOBRES
 (
   COD_PERSONA VARCHAR2(10) NOT NULL,
   NRO_SOBRE NUMBER(7,0) NOT NULL,
   ANO NUMBER(4,0) NOT NULL,
   MES NUMBER(2,0) NOT NULL,
   QUINCENA NUMBER(1,0) NOT NULL,
   NRO_PATRONAL NUMBER(15,0),
   FEC_CALCULO DATE NOT NULL,
   IND_PAGADO VARCHAR2(1) DEFAULT 'N',
   USU_INSERCION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
   FEC_INSERCION DATE DEFAULT SYSDATE NOT NULL,
   USU_MODIFICACION VARCHAR2(10) DEFAULT SUBSTR(USER,1,10) NOT NULL,
   FEC_MODIFICACION DATE DEFAULT SYSDATE NOT NULL
 );
COMMENT ON TABLE WKSP_WSFDC.RH_SOBRES IS 'Sobres de Liquidación del Empleado';
COMMENT ON COLUMN WKSP_WSFDC.RH_SOBRES.COD_PERSONA IS 'Codigo de la persona';
COMMENT ON COLUMN WKSP_WSFDC.RH_SOBRES.NRO_SOBRE IS 'Numero de Sobre';
COMMENT ON COLUMN WKSP_WSFDC.RH_SOBRES.ANO IS 'Año al cual corresponde el salario';
COMMENT ON COLUMN WKSP_WSFDC.RH_SOBRES.MES IS 'Mes al cual corresponde el salario';
COMMENT ON COLUMN WKSP_WSFDC.RH_SOBRES.QUINCENA IS 'Quincena a la cual corresponde el salario';
COMMENT ON COLUMN WKSP_WSFDC.RH_SOBRES.NRO_PATRONAL IS 'Número patronal de IPS que corresponde al Empleado.';
COMMENT ON COLUMN WKSP_WSFDC.RH_SOBRES.FEC_CALCULO IS 'Fecha en que se realizó el cálculo de sueldo.';
--Grant/Revoke object privileges
grant select, insert, update, delete on WKSP_WSFDC.RH_SOBRES to PUBLIC;
